language: node
sudo: false

env:
  global:
    - CF_DEPLOY_USER=fec_deployer
    - secure: "mMnoeISok8WzzgTp2fNCEwxr82vj/Y9fbfRuwtMbs0gkUnbJ8Rgn66CXdH8e8fXhwP37DAd3Q7/Z06b5aNIBLdSwc0t/New7foIXYNZUhaci+C3kYQfAQNe2owiSCPixtqKpYOCYe0XWulX02VrBS+6XB+P7TqeblGim6nyJoC1OqkiAqKF1gFwee1srQa58VqfowmUmgizjML8KrX5UiDRT4ai+WR7LeT29swPdUh91UBCvA7ejskyPGtDMx+u7w/2VxL3yVwjjsJs4WPzye3uzS2N6D77GjgcpoAVjg4EM1Lgu2LfzBNdFZdHJlusHeASz/YszPQldaTTxFzuXH8o7iNJWWht0xBQpotF0nMkpZqEMiu+Reug4dggT4XLQJB29cpg+aOxVL5SQadrf+9K7RZLCtgR0pybb5Uh3kAHM2krJocOURzcf2gIchkBsDFzuzRdnKXnJR8M41aFKiuTvz/yzD3DEE3DihaTt0+BiATCoSVQixvu3lwBdsX4D5zevE8VWbjY75GhBa8OrfiUK8ftxOt3tYS9kN3CihHK5d6+QP/R9Z1ZLhGp1+hsBQvy4W/PzttZiqyseLAnWbJPZZGCz4KT1dy4QIMrqVsZS9Wn3UeOjVL8QRoHiXEzjozrj4IGc8pMpeCA+GTeasQcxr8AvfjFk5vtwE/XChOw=" # CF_DEPLOY_PASSWORD

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh eregs fec dev manifest.dev.yml
    on:
      branch: feature/travis-deploy
