language: node_js

sudo: false

env:
  global:
    - CF_DEPLOY_USER=fec_deployer
    - secure: "N9za4Z/kWXXUaJO9pXLBzgBqLqxW0jXQne8DZyTqYbK/F+hF9T7SLMI1BwyPlksDlKP4nU1RRPBc9B2CkkdDGQSD4dHoYpy6kCTJ6ivxY6bQKjG5SzMokSFzLYJPKYUD1Ht/oq/OxOlxM8kZAqhBHkXK8bUbyneIg6yk+cPQFtb9rWFcUN7r7ottfQ+T4j1/VTbCX5P2mqPcrwUYJUoMd0hVf4SA2EY9id3z8BgdV2XTlDXTVB1lvHYbtpTPLqMM0aonjQ8uAo4PZidtTQAUP7gnhU9/I1zjUL1nygSnX8Ktkq5dQu2YY4bBzaHFrNIBpmXeSW+ubWP+lUEJr3N/rwxAakkoN9W+VVjpTD1lYl9w2ifqs58EPvjVDETuEbUzSqXBq2oRTXk38H8pfqhTa4XvZ9cm16kzOYJam37B/C8BGoifc8Kac7/Rf2EutUTJjMKyBOfJ4s3NQSnHRLTeecp0LFXEJCf6p0iMl6PW3tU0Y/fb3NRdEUb1R9X3d3gsNGffpQNe4sh874Qc4Wee2ZsMd5Bal0Z75tYcSIe5RZ8ggj03uhj4Whp+MeVOPO7FYd4hjWmoUR/QZYqEl1Tn9I6Hz3Esm6DPA7zWTPlABSWMCZkHlc/ZsllDcLEQRcWuy/xts8QhFLqhJya6mkL4Hm02kf+a2E5Mej3sUyeUBxg=" # CF_DEPLOY_PASSWORD

before_deploy:
  - mkdir $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - travis_retry curl -L "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.23.0" | tar xzv -C $HOME/bin
  - travis_retry cf install-plugin autopilot -f -r CF-Community

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/cf_deploy.sh fec-pattern-library fec dev manifest.dev.yml
    on:
      branch: feature/travis-deploy
